services:
  # Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: fastapi_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fastapi_net

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    # *** HACK DE TIEMPO: ESPERA 30 SEGUNDOS A QUE MYSQL ESTÉ LISTO ***
    command: ["/bin/bash", "-c", "sleep 60 && uvicorn main:app --host 0.0.0.0 --port 8000"]
    networks:
      - fastapi_net

  # Frontend (Angular)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fastapi_frontend
    restart: always
    ports:
      - "4200:8080"
    depends_on:
      - backend
    networks:
      - fastapi_net

volumes:
  db_data:

networks:
  fastapi_net: